In [50]:
'''
Q10: Produce a list of facilities with a total revenue less than 1000.
The output of facility name and total revenue, sorted by revenue. 
Remember that there's a different cost for guests and members!
'''
import sqlite3
from sqlite3 import Error
 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn
 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
SELECT sub1.name, sub1.total_revenue
FROM 
    (SELECT b.facid, f.name, 
            SUM(CASE WHEN memid =0 THEN slots * guestcost
				     ELSE slots * membercost
				     END ) AS total_revenue
     FROM Bookings AS b
     LEFT JOIN Facilities AS f ON b.facid = f.facid
     GROUP BY b.facid) AS sub1
WHERE sub1.total_revenue < 1000
ORDER BY total_revenue
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)
database = "country_club_sqlite.db"
 
# create a database connection
conn = create_connection(database)
with conn: 
    print("2. Query all tasks")
    select_all_tasks(conn)

2.6.0
2. Query all tasks
('Table Tennis', 180)
('Snooker Table', 240)
('Pool Table', 270)

In [48]:
'''
Q11: Produce a report of members and who recommended them in alphabetic surname,firstname order
'''
import sqlite3
from sqlite3 import Error
 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn
 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
SELECT (m1.surname ||' '||m1.firstname) as member_name, (m2.surname||' '||m2.firstname) AS recommended_name
FROM Members AS m1
JOIN Members AS m2
ON m1.recommendedby = m2.memid
ORDER BY member_name, recommended_name;
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)
database = "country_club_sqlite.db"
 
# create a database connection
conn = create_connection(database)
with conn: 
    print("2. Query all tasks")
    select_all_tasks(conn)

2.6.0
2. Query all tasks
('Bader Florence', 'Stibbons Ponder')
('Baker Anne', 'Stibbons Ponder')
('Baker Timothy', 'Farrell Jemima')
('Boothe Tim', 'Rownam Tim')
('Butters Gerald', 'Smith Darren')
('Coplin Joan', 'Baker Timothy')
('Crumpet Erica', 'Smith Tracy')
('Dare Nancy', 'Joplette Janice')
('Genting Matthew', 'Butters Gerald')
('Hunt John', 'Purview Millicent')
('Jones David', 'Joplette Janice')
('Jones Douglas', 'Jones David')
('Joplette Janice', 'Smith Darren')
('Mackenzie Anna', 'Smith Darren')
('Owen Charles', 'Smith Darren')
('Pinker David', 'Farrell Jemima')
('Purview Millicent', 'Smith Tracy')
('Rumney Henrietta', 'Genting Matthew')
('Sarwin Ramnaresh', 'Bader Florence')
('Smith Jack', 'Smith Darren')
('Stibbons Ponder', 'Tracy Burton')
('Worthington-Smyth Henry', 'Smith Tracy')

In [47]:
'''
Q12: Find the facilities with their usage by member, but not guests
'''
import sqlite3
from sqlite3 import Error
 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn
 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
SELECT f.name, SUM(sub.total_slots) as total_usage
FROM 
    (SELECT facid, SUM(slots) AS total_slots
	 FROM Bookings
	 WHERE memid !=0
	 GROUP BY memid
     ORDER BY facid) AS sub
LEFT JOIN Facilities AS f
ON sub.facid = f.facid
GROUP BY sub.facid;
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)
        
database = "country_club_sqlite.db"
 
# create a database connection
conn = create_connection(database)
with conn: 
    print("2. Query all tasks")
    select_all_tasks(conn)

2.6.0
2. Query all tasks
('Tennis Court 1', 1575)
('Tennis Court 2', 1803)
('Badminton Court', 881)
('Table Tennis', 865)
('Massage Room 1', 1205)
('Massage Room 2', 131)
('Snooker Table', 331)

In [ ]:
#Q13

In [46]:
'''
Q13: Find the facilities usage by month, but not guests
'''

import sqlite3
from sqlite3 import Error
 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn
 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
SELECT f.name, SUM(sub.total_slots) as total_usage
FROM 
     (SELECT facid, strftime('%m',starttime) AS "Month", SUM(slots) AS total_slots
	  FROM Bookings
	  WHERE memid !=0
	  GROUP BY "Month"
      ORDER BY facid) AS sub
LEFT JOIN Facilities AS f
ON sub.facid = f.facid
GROUP BY sub.facid;
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)
        
database = "country_club_sqlite.db"
 
# create a database connection
conn = create_connection(database)
with conn: 
    print("2. Query all tasks")
    select_all_tasks(conn)

2.6.0
2. Query all tasks
('Tennis Court 1', 5730)
('Table Tennis', 1061)